[book]
authors = ["Madhav Shekhar"]
language = "en"
multilingual = false
src = "src"
title = "w.mdvsh.co"
description = "madhav's personal wiki"

[build]
create-missing = true

[output.html]
preferred-dark-theme = "navy"
curly-quotes = true
mathjax-support = true
git-repository-url = "https://github.com/mdvsh/w"
git-repository-icon = "fa-github"
cname = "w.mdvsh.co"